project:
  type: website

website:
  title: "OurWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
        - icon: github
          menu:
            - text: Source Code
              url:  https://github.com/Sevnhutsjr/LSE-DS105-Wandermetrics
            - text: Report a Bug
              url:  https://github.com/Sevnhutsjr/LSE-DS105-Wandermetrics/issues/new/choose
          







format:
  html:
    theme: yeti
    css: styles.css
    toc: true






