project:
  type: website

website:
  title: "WanderMetrics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
        - icon: github
          menu:
            - text: Source Code
              url:  https://github.com/Sevnhutsjr/LSE-DS105-Wandermetrics
            - text: Report a Bug
              url:  https://github.com/Sevnhutsjr/LSE-DS105-Wandermetrics/issues/new/choose
  
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Data"
        contents:
          - Data_Collection.qmd
          
          
      - section: "Visualisations"
        contents:
          - instruction.qmd
          - Athens.qmd
          - Berlin.qmd
          - Budapest.qmd
          - Lisbon.qmd
          - Madrid.qmd
          - Paris.qmd
          - Rome.qmd
      
      - section: "Further Analysis"
        contents:
          - Time_Window_Analysis.qmd

      - section: "Findings"
        contents:
          - Conclusion.qmd
          







format:
  html:
    theme: yeti
    css: styles.css
    toc: true






