project:
  type: website

website:
  title: "OurWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd

      - section: "Layout"
        contents:
          - Berlin.md
          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



